# -*- coding: utf-8 -*-
"""playing_with_for_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrLfBs8hceP2F4UWZVMTKrVKz8XN0m_y
"""

n=2
for i in range (n):
  print("*")

# ['***']
empty_list = [] # after 1 loop ['*'] after 2nd loop ['*'(this is present in first loop =), '*']
n=3
empty_list.append("*"*n)
print(empty_list)

# ['***','***'] n=2 , m=3
empty_list = []
n=2
m=3
for i in range (0,n):

  empty_list.append("*"*m)
print(empty_list)

# ['***','***','***']
empty = []
n=3
for i in range (n):
  empty.append("*"*n)
print(empty)

# ['***','###','***']  # stupid method
empty = []
a=3
b=3
c=3
for i in range(a-2):
  empty.append("*"*a)
for j in range(b-2):
  empty.append("#"*b)
for k in range(c-2):
  empty.append("*"*c)
print(empty)

# ['***','###','***']
empty = []
n=3
m=3

for i in range (n):
  if i%2 == 0 :
    empty.append("*"*m)
  else :
    empty.append("#"*m)
print(empty)

# ['***','***','###']
empty = []
n=3
m=3
for i in range (n):
  if i<2 :
    empty.append("*"*m)
  else :
    empty.append("#"*m)
print(empty)

